name: ESP32 Build Check

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build ESP32 Firmware
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: platformio run
